"""empty message

Revision ID: 1ab54d477ffe
Revises: d0c49fcc0c6d
Create Date: 2021-04-23 17:23:53.833292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab54d477ffe'
down_revision = 'd0c49fcc0c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy', 'name')
    # ### end Alembic commands ###
