"""empty message

Revision ID: b904feb391e4
Revises: 1ab54d477ffe
Create Date: 2021-04-23 17:27:46.086992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b904feb391e4'
down_revision = '1ab54d477ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buy', 'price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buy', 'price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
